
name: Flask app Hola

on:
  push:
    branches: [ "main" , "Alexander"]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
   
    - name: Construir imagen de Docker
      run: |
        docker build -t ghcr.oi/alexander738022/holaflask:1.0.0 .

    - name: Login hacia GitHub Container Registry
      run : |
        echo ${{ secrets.GITHUB_WR }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Publicar la imagen creada
      run: |
        docker push ghcr.io/alexander738022/holaflask:1.0.0
